name: Nginx Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      - '.env'
  workflow_dispatch:

jobs:
  deploy-nginx:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove existing container
        run: |
          docker-compose down
        continue-on-error: true # Игнорируем ошибки, если контейнер не существует

      - name: Deploy Nginx with Docker Compose
        run: |
          docker-compose up -d

      - name: Verify Nginx is running
        run: |
          Start-Sleep -Seconds 5 # Ждем 5 секунд для запуска (PowerShell синтаксис)
          $response = Invoke-WebRequest -Uri http://localhost:8080 -UseBasicParsing
          if ($response.Content -match "Welcome to nginx") {
            Write-Output "Nginx is running correctly!"
          } else {
            Write-Output "Nginx failed to respond"
            exit 1
          }
