name: Nginx Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'compose.yml' # Триггер при изменении compose файла
      - '.env' # Триггер при изменении .env
  workflow_dispatch: # Для ручного запуска

jobs:
  deploy-nginx:
    runs-on: self-hosted # Твой self-hosted раннер
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove existing container
        run: |
          docker-compose down || true # Останавливаем и удаляем, игнорируя ошибки, если контейнера нет

      - name: Deploy Nginx with Docker Compose
        run: |
          docker-compose up -d # Запускаем контейнер в detached mode

      - name: Verify Nginx is running
        run: |
          sleep 5 # Даем время на запуск
          if curl -s http://localhost:8080 | grep -q "Welcome to nginx"; then
            echo "Nginx is running correctly!"
          else
            echo "Nginx failed to respond"
            exit 1
          fi
